---
title: "stl_lead_inequity"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
stl_lead<- read_csv(here::here("data","stl_lead.csv")) %>% 
  clean_names()

```

## Summary Statistics/ Initial Exploration

```{r}
summary(stl_lead)

ggplot(data = stl_lead, mapping = aes(x = (black/total_pop)*100, y = pct_elevated)) +
  geom_point()+
  labs(x= " Percent Black", y= " Percent Elevated")
```

```{r}
stl_lead_prop<-  stl_lead %>% mutate(propwhite= white/ total_pop )

stl_lead_plot <- ggplot(data = stl_lead_prop,aes(x = propwhite, y = pct_elevated, color="red"))+
  labs(x= " Percent White", y= " Percent Elevated")+
  geom_point()
stl_lead_plot
  
```

```{r}
ggsave(stl_lead_plot,file= "figs/stl_lead_plot.png",height= 5, width = 6 )


```

This graph shows that as the population is increasingly more white, eleveated blood pressure percentage decreases.

```{r}
pct_elevate_hist<- ggplot(data= stl_lead, aes(x= pct_elevated))+
  geom_histogram(color="red", fill= "white", linetype="dashed")

```

```{r}
ggsave(pct_elevate_hist,file="figs/pct_elevated_plot.png")
```
